# Generated by Django 5.1.3 on 2024-11-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIRTUAL TABLE vec_knowledge USING vec0(
                embedding FLOAT[1024]
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS vec_knowledge;",
        ),
    ]

