# Generated by Django 5.1.2 on 2024-11-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0002_create_vec_knowledge_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeEmbedding",
            fields=[
                (
                    "knowledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="rag.knowledge",
                    ),
                ),
                ("embedding", models.BinaryField()),
            ],
            options={
                "db_table": "vec_knowledge",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="knowledge",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rag.uploadfile",
            ),
        ),
    ]
